# Generated by Django 2.2.3 on 2021-10-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20211011_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='detail',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
